OBJS = \
	src/XGetHClrs.o \
	src/bridge.o \
	src/display.o \
	src/dither.o \
	src/editor.o \
	src/entities.o \
	src/forms.o \
	src/gif.o \
	src/history.o \
	src/html.o \
	src/icon.o \
	src/image.o \
	src/jpeg.o \
	src/mailcap.o \
	src/math.o \
	src/menu.o \
	src/neweditor.o \
	src/parsecommand.o \
	src/parsehtml.o \
	src/png.o \
	src/popup.o \
	src/scrollbar.o \
	src/status.o \
	src/style.o \
	src/toolbar.o \
	src/tools.o \
	src/util.o \
	src/www.o \
	src/x11.o

PNGOBJS = \
	libpng/png.o \
	libpng/pngerror.o \
	libpng/pngio.o \
	libpng/pngmem.o \
	libpng/pngpread.o \
	libpng/pngrcb.o \
	libpng/pngread.o \
	libpng/pngrtran.o \
	libpng/pngrutil.o \
	libpng/pngtrans.o \
	libpng/pngwrite.o \
	libpng/pngwtran.o \
	libpng/pngwutil.o

WWWOBJS = \
	libwww/src/HTAABrow.o \
	libwww/src/HTAAUtil.o \
	libwww/src/HTAccess.o \
	libwww/src/HTAlert.o \
	libwww/src/HTAnchor.o \
	libwww/src/HTArray.o \
	libwww/src/HTAssoc.o \
	libwww/src/HTAtom.o \
	libwww/src/HTBInit.o \
	libwww/src/HTBTree.o \
	libwww/src/HTBind.o \
	libwww/src/HTBound.o \
	libwww/src/HTCache.o \
	libwww/src/HTChunk.o \
	libwww/src/HTConLen.o \
	libwww/src/HTDNS.o \
	libwww/src/HTDescpt.o \
	libwww/src/HTDialog.o \
	libwww/src/HTDir.o \
	libwww/src/HTEPtoCl.o \
	libwww/src/HTError.o \
	libwww/src/HTEscape.o \
	libwww/src/HTEvntrg.o \
	libwww/src/HTFTP.o \
	libwww/src/HTFTPDir.o \
	libwww/src/HTFWrite.o \
	libwww/src/HTFile.o \
	libwww/src/HTFormat.o \
	libwww/src/HTGopher.o \
	libwww/src/HTGuess.o \
	libwww/src/HTHeader.o \
	libwww/src/HTHist.o \
	libwww/src/HTHome.o \
	libwww/src/HTIcons.o \
	libwww/src/HTInit.o \
	libwww/src/HTList.o \
	libwww/src/HTLog.o \
	libwww/src/HTMIME.o \
	libwww/src/HTMIMERq.o \
	libwww/src/HTML.o \
	libwww/src/HTMLGen.o \
	libwww/src/HTMLPDTD.o \
	libwww/src/HTMemory.o \
	libwww/src/HTMethod.o \
	libwww/src/HTMulti.o \
	libwww/src/HTNDir.o \
	libwww/src/HTNet.o \
	libwww/src/HTNetTxt.o \
	libwww/src/HTNews.o \
	libwww/src/HTNewsLs.o \
	libwww/src/HTNewsRq.o \
	libwww/src/HTParse.o \
	libwww/src/HTPlain.o \
	libwww/src/HTProt.o \
	libwww/src/HTProxy.o \
	libwww/src/HTReqMan.o \
	libwww/src/HTRules.o \
	libwww/src/HTSocket.o \
	libwww/src/HTString.o \
	libwww/src/HTStyle.o \
	libwww/src/HTTCP.o \
	libwww/src/HTTP.o \
	libwww/src/HTTPGen.o \
	libwww/src/HTTPReq.o \
	libwww/src/HTTPRes.o \
	libwww/src/HTTPServ.o \
	libwww/src/HTTeXGen.o \
	libwww/src/HTTee.o \
	libwww/src/HTTelnet.o \
	libwww/src/HTUU.o \
	libwww/src/HTWSRC.o \
	libwww/src/HTWWWStr.o \
	libwww/src/HTWriter.o \
	libwww/src/HTXParse.o \
	libwww/src/SGML.o
